//
//  ShowNameWorkerTests.swift
//  VipTddApp
//
//  Created by Jakub Hutny on 21.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import VipTddApp
import XCTest

class ShowNameWorkerTests: XCTestCase
{
    // MARK: - Subject under test
  
    var sut: ShowNameWorker!
  
    // MARK: - Test lifecycle
  
    override func setUp()
    {
        super.setUp()
        setupShowNameWorker()
    }
  
    override func tearDown()
    {
        super.tearDown()
    }
  
    // MARK: - Test setup
  
    func setupShowNameWorker()
    {
        sut = ShowNameWorker()
    }
  
    // MARK: - Test doubles
  
    // MARK: - Tests
    
    func testShouldReturnProperMessageWhenTextContainsLettersOnly() {
        // Given
        let text = "TestName"
        let expectedMessage = "So you’re name is " + text
        
        // When
        let message = sut.createMessage(text: text)
        
        // Then
        XCTAssertEqual(message, expectedMessage, "Message is different than expected.")
        XCTAssertEqual(sut.isRealName, true)
    }
    
    func testShouldReturnProperMessageWhenTextDoesNotContainLettersOnly() {
        // Given
        let text = "TestName123"
        let expectedMessage = "I guess " + text + " is not your name, is it?"
        
        // When
        let message = sut.createMessage(text: text)
        
        // Then
        XCTAssertEqual(message, expectedMessage, "Message is different than expected.")
        XCTAssertEqual(sut.isRealName, false)
    }
}
