//
//  ShowNameInteractorTests.swift
//  VipTddApp
//
//  Created by Jakub Hutny on 21.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import VipTddApp
import XCTest

class ShowNameInteractorTests: XCTestCase
{
    // MARK: - Subject under test
  
    var sut: ShowNameInteractor!
  
    // MARK: - Test lifecycle
  
    override func setUp()
    {
        super.setUp()
        setupShowNameInteractor()
    }
  
    override func tearDown()
    {
        super.tearDown()
    }
  
    // MARK: - Test setup
  
    func setupShowNameInteractor()
    {
        sut = ShowNameInteractor()
    }
  
    // MARK: - Test doubles
    
    class ShowNameInteractorOutputStub: ShowNameInteractorOutput {
        var presentLabelMessageCalled = false
        
        func presentLabelMessage(response: ShowName.DisplayMessage.Response) {
            presentLabelMessageCalled = true
        }
    }
    
    class ShowNameWorkerStub: ShowNameWorker {
        var createMessageCalled = false
        
        override func createMessage(text: String) -> String {
            createMessageCalled = true
            
            return ""
        }
    }
  
    // MARK: - Tests
    
    func testShouldCallPresenterToFormatLabelMessage() {
        // Given
        let showNameInteractorOutputStub = ShowNameInteractorOutputStub()
        let showNameWorkerStub = ShowNameWorkerStub()
        sut.output = showNameInteractorOutputStub
        sut.worker = showNameWorkerStub
        let request = ShowName.DisplayMessage.Request(text: "ABC")
        
        // When
        sut.createLabelMessage(request: request)
        
        // Then
        XCTAssertEqual(showNameInteractorOutputStub.presentLabelMessageCalled, true, "Interactor should call Presenter to format label message.")
    }

}
