//
//  ShowNameWorkerTests.swift
//  VipTddApp
//
//  Created by Jakub Hutny on 21.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import VipTddApp
import XCTest

class ShowNameWorkerTests: XCTestCase
{
  // MARK: - Subject under test
  
  var sut: ShowNameWorker!
  
  // MARK: - Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupShowNameWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupShowNameWorker()
  {
    sut = ShowNameWorker()
  }
  
  // MARK: - Test doubles
  
  // MARK: - Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
