//
//  ShowNameConfigurator.swift
//  VipTddApp
//
//  Created by Jakub Hutny on 21.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ShowNameViewController: ShowNamePresenterOutput
{
    func displaySomething(viewModel: ShowName.Something.ViewModel) {
    
    }

  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ShowNameInteractor: ShowNameViewControllerOutput
{
}

extension ShowNamePresenter: ShowNameInteractorOutput
{
}

class ShowNameConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ShowNameConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ShowNameViewController)
  {
    let router = ShowNameRouter()
    router.viewController = viewController
    
    let presenter = ShowNamePresenter()
    presenter.output = viewController
    
    let interactor = ShowNameInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
