//
//  ShowNameInteractor.swift
//  VipTddApp
//
//  Created by Jakub Hutny on 21.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowNameInteractorInput
{
    func createLabelMessage(request: ShowName.DisplayMessage.Request)
}

protocol ShowNameInteractorOutput
{
  func presentSomething(response: ShowName.Something.Response)
}

class ShowNameInteractor: ShowNameInteractorInput
{
  var output: ShowNameInteractorOutput!
  var worker: ShowNameWorker!
  
  // MARK: - Business logic
    
    // to be updated
    func createLabelMessage(request: ShowName.DisplayMessage.Request) {
        
    }
  
  func doSomething(request: ShowName.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ShowNameWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ShowName.Something.Response()
    output.presentSomething(response: response)
  }
}
