//
//  ShowNameInteractor.swift
//  VipTddApp
//
//  Created by Jakub Hutny on 21.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowNameInteractorInput
{
    func createLabelMessage(request: ShowName.DisplayMessage.Request)
}

protocol ShowNameInteractorOutput
{
    func presentLabelMessage(response: ShowName.DisplayMessage.Response)
}

class ShowNameInteractor: ShowNameInteractorInput
{
    var output: ShowNameInteractorOutput!
    var worker: ShowNameWorker!
  
    // MARK: - Business logic
    
    func createLabelMessage(request: ShowName.DisplayMessage.Request) {
        worker = ShowNameWorker()
        let message = worker.createMessage(text: request.text)
        let number = worker.generateRandomIntegerNumber()
        let isRealName = worker.isRealName
        let response = ShowName.DisplayMessage.Response(message: message, number: number, isRealName: isRealName)
        output.presentLabelMessage(response: response)
    }
}
