//
//  ShowNameViewController.swift
//  VipTddApp
//
//  Created by Jakub Hutny on 21.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowNameViewControllerInput
{
    func displayLabelMessage(viewModel: ShowName.DisplayMessage.ViewModel)
}

protocol ShowNameViewControllerOutput
{
    func createLabelMessage(request: ShowName.DisplayMessage.Request)
}

class ShowNameViewController: UIViewController, ShowNameViewControllerInput
{
    var output: ShowNameViewControllerOutput!
    var router: ShowNameRouter!
  
    @IBOutlet var inputTextField: UITextField!
    @IBOutlet var outputLabel: UILabel!
    
    // MARK: - Object lifecycle
  
    override func awakeFromNib()
    {
        super.awakeFromNib()
        ShowNameConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // These two functions are added to invoke EndEditing event when user taps outside the text field.
    // They might be provided via VIP cycle, but in case of usefulness, they were handled this way.
    
    func dismissKeyboardWhenTap() {
        self.view.addGestureRecognizer(UITapGestureRecognizer(target: self, action:#selector(ShowNameViewController.dismissKeyboard)))
    }
    
    func dismissKeyboard() {
        view.endEditing(true)
    }
  
    // MARK: - View lifecycle
  
    override func viewDidLoad()
    {
        super.viewDidLoad()
        dismissKeyboardWhenTap()
    }
  
  // MARK: - Event handling
    
    @IBAction func inputTextFieldTextProvided(_ sender: UITextField) {
        let text = inputTextField.text!
        let request = ShowName.DisplayMessage.Request(text: text)
        output.createLabelMessage(request: request)
    }
    
  // MARK: - Display logic
    
    func displayLabelMessage(viewModel: ShowName.DisplayMessage.ViewModel) {
        outputLabel.text = viewModel.message
    }
  
}
