//
//  ShowNameModels.swift
//  VipTddApp
//
//  Created by Jakub Hutny on 21.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ShowName
{
    struct Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    struct DisplayMessage {
        struct Request {
            var text: String
        }
        struct Response {
            var message: String
            var number: Int
            var isRealName: Bool
        }
        struct ViewModel {
            
        }
    }
}
